#!/bin/python3

import os

if __name__ == "__main__":
    print("Current User:", os.getenv("USER"))
    print("User's Home Directory:", os.path.expanduser("~"))

    if os.access(os.path.expanduser("~/Downloads"), os.R_OK):
        print("Yes, I have read access to Downloads.")
    else:
        print("No, I do not have read access to Downloads.")

    if os.access(os.path.expanduser("~/Documents"), os.R_OK):
        print("Yes, I have read access to Documents.")
    else:
        print("No, I do not have read access to Documents.")

    if os.getenv("PERMISSIONS_GRANTED") is not None:
        if os.getenv("PERMISSIONS_GRANTED") == "...":
            print("No permissions have been granted.")
        else:
            print("Permissions granted:", os.getenv("PERMISSIONS_GRANTED"))
