#!/bin/python3

import os

if __name__ == "__main__":
    print("Current User:", os.getenv("USER"))
    print("User's Home Directory:", os.path.expanduser("~"))

    print(os.listdir(os.path.expanduser("~")))

    if os.access(os.path.expanduser("~/Downloads"), os.R_OK):
        print("Yes, I have read access to Downloads.")
    else:
        print("No, I do not have read access to Downloads.")

    if os.access(os.path.expanduser("~/Documents"), os.R_OK):
        print("Yes, I have read access to Documents.")
    else:
        print("No, I do not have read access to Documents.")

    if os.access(os.path.expanduser("/sys"), os.R_OK):
        print("Yes, I have read access to /sys.")
    else:
        print("No, I do not have read access to /sys.")
